apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      # AÑADE ESTA SECCIÓN
      imagePullSecrets:
        - name: acr-secret
      # FIN DE LA SECCIÓN
      containers:
        - name: worker
          image: acrcicddemo18093.azurecr.io/worker:latest
